export const booklist = [
  {
    id: 1,
    img: "https://images-na.ssl-images-amazon.com/images/I/41eOX0cBT8L._AC_SX184_.jpg",
    title: "Milkman: A Novel",
    author: "Anna Burns",
  },
  {
    id: 2,
    img: "https://images-na.ssl-images-amazon.com/images/I/51ZBaKBB3ML._AC_SX184_.jpg",
    title: "What My Bones Know",
    author: "Stephanie Foo",
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/91xUsdujK3L._AC_UL320_.jpg",
    title: "Cat Kid Comic Club",
    author: "Editors' pick",
  },
  {
    id: 4,
    img: "https://images-na.ssl-images-amazon.com/images/I/51pFNnDSdeL._AC_SX184_.jpg",
    title: "River of the Gods",
    author: "Candice Millard",
  },
  {
    id: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/51-aB6gtJZL._AC_SX184_.jpg",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/510sYnD2ezS._AC_SX184_.jpg",
    title: "Sleepwalk",
    author: "Dan Chaon",
  },
  {
    id: 7,
    img: "https://images-na.ssl-images-amazon.com/images/I/51O9e2PaOyL._AC_SX184_.jpg",
    title: "The Kaiju Preservation Society",
    author: "John Scalzi",
  },
  {
    id: 8,
    img: "https://images-na.ssl-images-amazon.com/images/I/41ZO-a-gSFL._AC_SX184_.jpg",
    title: "Unmasked: My Life Solving America's",
    author: "Paul Holes",
  },
  {
    id: 9,
    img: "https://images-na.ssl-images-amazon.com/images/I/51UKwFYx89L._AC_SX184_.jpg",
    title: "Black Cake: A Novel",
    author: "Charmaine Wilkerson",
  },
  {
    id: 10,
    img: "https://images-na.ssl-images-amazon.com/images/I/41eOX0cBT8L._AC_SX184_.jpg",
    title: "Milkman: A Novel",
    author: "Anna Burns",
  },
  {
    id: 11,
    img: "https://images-na.ssl-images-amazon.com/images/I/51ZBaKBB3ML._AC_SX184_.jpg",
    title: "What My Bones Know",
    author: "Stephanie Foo",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/91xUsdujK3L._AC_UL320_.jpg",
    title: "Cat Kid Comic Club",
    author: "Editors' pick",
  },
  {
    id: 13,
    img: "https://images-na.ssl-images-amazon.com/images/I/51pFNnDSdeL._AC_SX184_.jpg",
    title: "River of the Gods",
    author: "Candice Millard",
  },
  {
    id: 14,
    img: "https://images-na.ssl-images-amazon.com/images/I/51-aB6gtJZL._AC_SX184_.jpg",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
  },
  {
    id: 15,
    img: "https://images-na.ssl-images-amazon.com/images/I/510sYnD2ezS._AC_SX184_.jpg",
    title: "Sleepwalk",
    author: "Dan Chaon",
  },
  {
    id: 16,
    img: "https://images-na.ssl-images-amazon.com/images/I/51O9e2PaOyL._AC_SX184_.jpg",
    title: "The Kaiju Preservation Society",
    author: "John Scalzi",
  },
  {
    id: 17,
    img: "https://images-na.ssl-images-amazon.com/images/I/41ZO-a-gSFL._AC_SX184_.jpg",
    title: "Unmasked: My Life Solving America's",
    author: "Paul Holes",
  },
  {
    id: 18,
    img: "https://images-na.ssl-images-amazon.com/images/I/51UKwFYx89L._AC_SX184_.jpg",
    title: "Black Cake: A Novel",
    author: "Charmaine Wilkerson",
  },
  {
    id: 19,
    img: "https://images-na.ssl-images-amazon.com/images/I/41eOX0cBT8L._AC_SX184_.jpg",
    title: "Milkman: A Novel",
    author: "Anna Burns",
  },
  {
    id: 20,
    img: "https://images-na.ssl-images-amazon.com/images/I/51ZBaKBB3ML._AC_SX184_.jpg",
    title: "What My Bones Know",
    author: "Stephanie Foo",
  },
  {
    id: 21,
    img: "https://m.media-amazon.com/images/I/91xUsdujK3L._AC_UL320_.jpg",
    title: "Cat Kid Comic Club",
    author: "Editors' pick",
  },
  {
    id: 22,
    img: "https://images-na.ssl-images-amazon.com/images/I/51pFNnDSdeL._AC_SX184_.jpg",
    title: "River of the Gods",
    author: "Candice Millard",
  },
  {
    id: 23,
    img: "https://images-na.ssl-images-amazon.com/images/I/51-aB6gtJZL._AC_SX184_.jpg",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
  },
  {
    id: 24,
    img: "https://images-na.ssl-images-amazon.com/images/I/510sYnD2ezS._AC_SX184_.jpg",
    title: "Sleepwalk",
    author: "Dan Chaon",
  },
  {
    id: 25,
    img: "https://images-na.ssl-images-amazon.com/images/I/51O9e2PaOyL._AC_SX184_.jpg",
    title: "The Kaiju Preservation Society",
    author: "John Scalzi",
  },
  {
    id: 26,
    img: "https://images-na.ssl-images-amazon.com/images/I/41ZO-a-gSFL._AC_SX184_.jpg",
    title: "Unmasked: My Life Solving America's",
    author: "Paul Holes",
  },
  {
    id: 27,
    img: "https://images-na.ssl-images-amazon.com/images/I/51UKwFYx89L._AC_SX184_.jpg",
    title: "Black Cake: A Novel",
    author: "Charmaine Wilkerson",
  },
  {
    id: 28,
    img: "https://images-na.ssl-images-amazon.com/images/I/41eOX0cBT8L._AC_SX184_.jpg",
    title: "Milkman: A Novel",
    author: "Anna Burns",
  },
  {
    id: 29,
    img: "https://images-na.ssl-images-amazon.com/images/I/51ZBaKBB3ML._AC_SX184_.jpg",
    title: "What My Bones Know",
    author: "Stephanie Foo",
  },
  {
    id: 30,
    img: "https://m.media-amazon.com/images/I/91xUsdujK3L._AC_UL320_.jpg",
    title: "Cat Kid Comic Club",
    author: "Editors' pick",
  },
  {
    id: 31,
    img: "https://images-na.ssl-images-amazon.com/images/I/51pFNnDSdeL._AC_SX184_.jpg",
    title: "River of the Gods",
    author: "Candice Millard",
  },
  {
    id: 32,
    img: "https://images-na.ssl-images-amazon.com/images/I/51-aB6gtJZL._AC_SX184_.jpg",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
  },
  {
    id: 33,
    img: "https://images-na.ssl-images-amazon.com/images/I/510sYnD2ezS._AC_SX184_.jpg",
    title: "Sleepwalk",
    author: "Dan Chaon",
  },
  {
    id: 34,
    img: "https://images-na.ssl-images-amazon.com/images/I/51O9e2PaOyL._AC_SX184_.jpg",
    title: "The Kaiju Preservation Society",
    author: "John Scalzi",
  },
  {
    id: 35,
    img: "https://images-na.ssl-images-amazon.com/images/I/41ZO-a-gSFL._AC_SX184_.jpg",
    title: "Unmasked: My Life Solving America's",
    author: "Paul Holes",
  },
  {
    id: 36,
    img: "https://images-na.ssl-images-amazon.com/images/I/51UKwFYx89L._AC_SX184_.jpg",
    title: "Black Cake: A Novel",
    author: "Charmaine Wilkerson",
  },
];
